# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[
  'Abaddon' ,
  'Alchemist' ,
  'Axe' ,
  'Beastmaster' ,
  'Brewmaster' ,
  'Bristleback' ,
  'Centaur' ,
  'Warrunner' ,
  'Chaos Knight' ,
  'Clockwerk' ,
  'Doom' ,
  'Dragon Knight' ,
  'Earth Spirit' ,
  'Earthshaker' ,
  'Elder Titan' ,
  'Huskar' ,
  'Io' ,
  'Kunkka' ,
  'Legion Commander' ,
  'Lifestealer' ,
  'Lycan' ,
  'Magnus' ,
  'Night Stalker' ,
  'Omniknight' ,
  'Phoenix' ,
  'Pudge' ,
  'Sand King' ,
  'Slardar' ,
  'Spirit Breaker' ,
  'Sven' ,
  'Tidehunter' ,
  'Timbersaw' ,
  'Tiny' ,
  'Treant' ,
  'Protector' ,
  'Tusk' ,
  'Underlord' ,
  'Undying' ,
  'Wraith King',
  'Anti-Mage' ,
  'Arc Warden' ,
  'Bloodseeker' ,
  'Bounty Hunter' ,
  'Broodmother' ,
  'Clinkz' ,
  'Drow Ranger' ,
  'Ember Spirit' ,
  'Faceless Void' ,
  'Gyrocopter' ,
  'Juggernaut' ,
  'Lone Druid' ,
  'Luna' ,
  'Medusa' ,
  'Meepo' ,
  'Mirana' ,
  'Monkey King' ,
  'Morphling' ,
  'Naga Siren' ,
  'Nyx Assassin' ,
  'Pangolier' ,
  'Phantom Assassin' ,
  'Phantom Lancer' ,
  'Razor' ,
  'Riki' ,
  'Shadow Fiend' ,
  'Slark' ,
  'Sniper' ,
  'Spectre' ,
  'Templar Assassin' ,
  'Terrorblade' ,
  'Troll Warlord' ,
  'Ursa' ,
  'Vengeful Spirit' ,
  'Venomancer' ,
  'Viper' ,
  'Weaver',
  'Ancient Apparition' ,
  'Bane' ,
  'Batrider' ,
  'Chen' ,
  'Crystal Maiden' ,
  'Dark Seer' ,
  'Dark Willow' ,
  'Dazzle' ,
  'Death Prophet' ,
  'Disruptor' ,
  'Enchantress' ,
  'Enigma' ,
  'Invoker' ,
  'Jakiro' ,
  'Keeper of the Light' ,
  'Leshrac' ,
  'Lich' ,
  'Lina' ,
  'Lion' ,
  "Nature's Prophet" ,
  'Necrophos' ,
  'Ogre Magi' ,
  'Oracle' ,
  'Outworld Devourer' ,
  'Puck',
  'Pugna',
  'Queen of Pain',
  'Rubick',
  'Shadow Demon',
  'Shadow Shaman',
  'Silencer',
  'Skywrath Mage',
  'Storm Spirit',
  'Techies',
  'Tinker',
  'Visage',
  'Warlock',
  'Windranger',
  'Winter Wyvern',
  'Witch Doctor',
  'Zeus',
].each do |hero_name|
  Hero.create!(name: hero_name)
end
